name: reddit_clone
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cloud_firestore: ^4.0.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.0.1
  firebase_core: ^2.0.0
  firebase_storage: ^11.0.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  fpdart: ^0.3.0
  google_sign_in: ^5.4.2
  routemaster: ^1.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #         weight: 700
